// <auto-generated />
using System;
using Inklume.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inklume.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260914145247_AddVisualEditorFoundation")]
    partial class AddVisualEditorFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.ChapterMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.PageMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PixelHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PixelWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "Number")
                        .IsUnique();

                    b.HasIndex("ChapterId", "RelativePath")
                        .IsUnique();

                    b.ToTable("Pages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pages_ContentHash_Length", "length(\"ContentHash\") = 64");

                            t.HasCheckConstraint("CK_Pages_Dimensions_Valid", "(\"PixelWidth\" IS NULL AND \"PixelHeight\" IS NULL) OR (\"PixelWidth\" > 0 AND \"PixelHeight\" > 0)");

                            t.HasCheckConstraint("CK_Pages_Number_Positive", "\"Number\" > 0");
                        });
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.ProjectMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.TextRegionMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContainerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GeometryKind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PageId", "ReadingOrder")
                        .IsUnique();

                    b.ToTable("TextRegions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TextRegions_ReadingOrder_Positive", "\"ReadingOrder\" > 0");
                        });
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.TextRegionPointMetadata", b =>
                {
                    b.Property<Guid>("TextRegionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("TextRegionId", "PointIndex");

                    b.ToTable("TextRegionPoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_TextRegionPoints_PointIndex_Nonnegative", "\"PointIndex\" >= 0");
                        });
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.ChapterMetadata", b =>
                {
                    b.HasOne("Inklume.Infrastructure.Persistence.ProjectMetadata", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.PageMetadata", b =>
                {
                    b.HasOne("Inklume.Infrastructure.Persistence.ChapterMetadata", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.TextRegionMetadata", b =>
                {
                    b.HasOne("Inklume.Infrastructure.Persistence.PageMetadata", null)
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.TextRegionPointMetadata", b =>
                {
                    b.HasOne("Inklume.Infrastructure.Persistence.TextRegionMetadata", null)
                        .WithMany("Points")
                        .HasForeignKey("TextRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inklume.Infrastructure.Persistence.TextRegionMetadata", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
