<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="WPF-UI" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Inklume.Application\Inklume.Application.csproj" />
        <ProjectReference Include="..\Inklume.Infrastructure\Inklume.Infrastructure.csproj" />
        <ProjectReference Include="..\Inklume.Imaging\Inklume.Imaging.csproj" />
    </ItemGroup>
</Project>
